export const CHANGE_TOP_BANNER = 'CHANGE_TOP_BANNER'
export const CHANGE_HOT_RECOMMEND = 'CHANGE_HOT_RECOMMEND'
export const CHANGE_NEW_ALBUM = 'CHANGE_NEW_ALBUM'
export const CHANGE_HOT_RANKING = 'CHANGE_HOT_RANKING'
export const CHANGE_NEW_RANKING = 'CHANGE_NEW_RANKING'
export const CHANGE_ORIGIN_RANKING = 'CHANGE_ORIGIN_RANKING'

export const CHANGE_SETTLE_SINGER = 'CHANGE_SETTLE_SINGER'



